### PR TITLE
fixed metadata type

### PR DESCRIPTION
**Pull request by EctoOne**
Fixed Error: requested mismatched theme type for [detailed.md_rating] - expected "rating", got "text"

### CODE REVIEW

**Comment by lilbud** [comment]
What, are you just going through all of my old themes and fixing them?

**Comment by EctoOne** [comment]
Sort of. :) 
I'm working on making some themes modular just for fun. Like the theme template I posted on the forum. And it's interesting to see what's possible and working with variables. Like the error I got when trying to use the system.fullName variable on system view.
And your themes are all pretty simple and don't require much work while moving around images and stuff. Also I like your themes the most.
And when I see an error pop up, why not fix it before I rip the theme apart. :D
I hope you don't mind it, I'm not going to announce that I'm doing that. So people can only find the modular variations if they search for it. I mean so far I've only done the assets separation on switch-dark.
If you do mind, I can remove the modular branch on my fork and just keep it on my laptop.

**Comment by lilbud** [comment]
are you modifying the themes directly, or are you creating a new branch?

**Comment by EctoOne** [comment]
I'm creating a new branch. Because I thought that was the best way. But like I said, I'm new to all this github stuff, so I have no idea what I'm doing. :)
I'm just bored and I enjoy messing around with stuff like this, and if I can help fix things it's even better.

**Pull request merged**
